apiVersion: v1
kind: Service
metadata:
  name: %STACK_NAME%
  labels:
    app: ai-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: ai-mysql
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: %STACK_NAME%
  labels:
    app: ai-mysql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ai-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: ai-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "my-secret-pw"
        - name: MYSQL_DATABASE
          value: "wordpress"
        - name: MYSQL_USER
          value: "wordpress"
        - name: MYSQL_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306
          name: ai-mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        awsElasticBlockStore:
          volumeID: vol-83e0093c
          fsType: ext4
