apiVersion: v1
kind: Service
metadata:
  name: %STACK_NAME%
  labels:
    app: nodejs
spec:
  ports:
    - port: 8080
  selector:
    app: nodejs
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: %STACK_NAME%
  labels:
    app: nodejs
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodejs
        tier: frontend
    spec:
      containers:
      - image: kopachevsky/ai-nodejs
        name: nodejs
        ports:
        - containerPort: 8080
          name: nodejs
