apiVersion: v1
kind: Service
metadata:
  name: %STACK_NAME%-nginx
  labels:
    app: %STACK_NAME%-nginx
spec:
  ports:
    - port: 80
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: %STACK_NAME%-nginx
  labels:
    app: nginx
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - image: kopachevsky/ai-nginx
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
